/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesIdRouteImport } from './routes/courses.$id'
import { Route as DashboardStudentRouteImport } from './routes/dashboard.student'
import { Route as DashboardTeacherRouteImport } from './routes/dashboard.teacher'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin.courses.index'
import { Route as AdminCoursesIdRouteImport } from './routes/admin.courses.$id'
import { Route as AdminSubscriptionsIndexRouteImport } from './routes/admin.subscriptions.index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as DashboardStudentIndexRouteImport } from './routes/dashboard.student.index'
import { Route as DashboardStudentLiveRouteImport } from './routes/dashboard.student.live'
import { Route as DashboardStudentOrdersRouteImport } from './routes/dashboard.student.orders'
import { Route as DashboardStudentProgressRouteImport } from './routes/dashboard.student.progress'
import { Route as DashboardTeacherIndexRouteImport } from './routes/dashboard.teacher.index'
import { Route as DashboardTeacherCoursesRouteImport } from './routes/dashboard.teacher.courses'
import { Route as DashboardTeacherLessonsRouteImport } from './routes/dashboard.teacher.lessons'
import { Route as DashboardTeacherLiveRouteImport } from './routes/dashboard.teacher.live'
import { Route as DashboardTeacherProgressRouteImport } from './routes/dashboard.teacher.progress'
import { Route as DashboardTeacherUploadsRouteImport } from './routes/dashboard.teacher.uploads'
import { Route as DashboardStudentCoursesIndexRouteImport } from './routes/dashboard.student.courses.index'
import { Route as DashboardStudentCoursesIdRouteImport } from './routes/dashboard.student.courses.$id'
import { Route as DashboardStudentQuizzesIndexRouteImport } from './routes/dashboard.student.quizzes.index'
import { Route as DashboardStudentQuizzesIdRouteImport } from './routes/dashboard.student.quizzes.$id'
import { Route as DashboardTeacherCoursesIndexRouteImport } from './routes/dashboard.teacher.courses.index'
import { Route as DashboardTeacherCoursesIdRouteImport } from './routes/dashboard.teacher.courses.$id'
import { Route as DashboardTeacherCoursesNewRouteImport } from './routes/dashboard.teacher.courses.new'
import { Route as DashboardTeacherQuizzesIndexRouteImport } from './routes/dashboard.teacher.quizzes.index'
import { Route as DashboardTeacherQuizzesIdRouteImport } from './routes/dashboard.teacher.quizzes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIdRoute = CoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStudentRoute = DashboardStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeacherRoute = DashboardTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesIdRoute = AdminCoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsIndexRoute = AdminSubscriptionsIndexRouteImport.update({
  id: '/subscriptions/',
  path: '/subscriptions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardStudentIndexRoute = DashboardStudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardStudentRoute,
} as any)
const DashboardStudentLiveRoute = DashboardStudentLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => DashboardStudentRoute,
} as any)
const DashboardStudentOrdersRoute = DashboardStudentOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardStudentRoute,
} as any)
const DashboardStudentProgressRoute =
  DashboardStudentProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => DashboardStudentRoute,
  } as any)
const DashboardTeacherIndexRoute = DashboardTeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardTeacherRoute,
} as any)
const DashboardTeacherCoursesRoute = DashboardTeacherCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardTeacherRoute,
} as any)
const DashboardTeacherLessonsRoute = DashboardTeacherLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => DashboardTeacherRoute,
} as any)
const DashboardTeacherLiveRoute = DashboardTeacherLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => DashboardTeacherRoute,
} as any)
const DashboardTeacherProgressRoute =
  DashboardTeacherProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => DashboardTeacherRoute,
  } as any)
const DashboardTeacherUploadsRoute = DashboardTeacherUploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => DashboardTeacherRoute,
} as any)
const DashboardStudentCoursesIndexRoute =
  DashboardStudentCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => DashboardStudentRoute,
  } as any)
const DashboardStudentCoursesIdRoute =
  DashboardStudentCoursesIdRouteImport.update({
    id: '/courses/$id',
    path: '/courses/$id',
    getParentRoute: () => DashboardStudentRoute,
  } as any)
const DashboardStudentQuizzesIndexRoute =
  DashboardStudentQuizzesIndexRouteImport.update({
    id: '/quizzes/',
    path: '/quizzes/',
    getParentRoute: () => DashboardStudentRoute,
  } as any)
const DashboardStudentQuizzesIdRoute =
  DashboardStudentQuizzesIdRouteImport.update({
    id: '/quizzes/$id',
    path: '/quizzes/$id',
    getParentRoute: () => DashboardStudentRoute,
  } as any)
const DashboardTeacherCoursesIndexRoute =
  DashboardTeacherCoursesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardTeacherCoursesRoute,
  } as any)
const DashboardTeacherCoursesIdRoute =
  DashboardTeacherCoursesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => DashboardTeacherCoursesRoute,
  } as any)
const DashboardTeacherCoursesNewRoute =
  DashboardTeacherCoursesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => DashboardTeacherCoursesRoute,
  } as any)
const DashboardTeacherQuizzesIndexRoute =
  DashboardTeacherQuizzesIndexRouteImport.update({
    id: '/quizzes/',
    path: '/quizzes/',
    getParentRoute: () => DashboardTeacherRoute,
  } as any)
const DashboardTeacherQuizzesIdRoute =
  DashboardTeacherQuizzesIdRouteImport.update({
    id: '/quizzes/$id',
    path: '/quizzes/$id',
    getParentRoute: () => DashboardTeacherRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/courses/$id': typeof CoursesIdRoute
  '/dashboard/student': typeof DashboardStudentRouteWithChildren
  '/dashboard/teacher': typeof DashboardTeacherRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/dashboard/student/live': typeof DashboardStudentLiveRoute
  '/dashboard/student/orders': typeof DashboardStudentOrdersRoute
  '/dashboard/student/progress': typeof DashboardStudentProgressRoute
  '/dashboard/teacher/courses': typeof DashboardTeacherCoursesRouteWithChildren
  '/dashboard/teacher/lessons': typeof DashboardTeacherLessonsRoute
  '/dashboard/teacher/live': typeof DashboardTeacherLiveRoute
  '/dashboard/teacher/progress': typeof DashboardTeacherProgressRoute
  '/dashboard/teacher/uploads': typeof DashboardTeacherUploadsRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/subscriptions/': typeof AdminSubscriptionsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/dashboard/student/': typeof DashboardStudentIndexRoute
  '/dashboard/teacher/': typeof DashboardTeacherIndexRoute
  '/dashboard/student/courses/$id': typeof DashboardStudentCoursesIdRoute
  '/dashboard/student/quizzes/$id': typeof DashboardStudentQuizzesIdRoute
  '/dashboard/teacher/courses/$id': typeof DashboardTeacherCoursesIdRoute
  '/dashboard/teacher/courses/new': typeof DashboardTeacherCoursesNewRoute
  '/dashboard/teacher/quizzes/$id': typeof DashboardTeacherQuizzesIdRoute
  '/dashboard/student/courses/': typeof DashboardStudentCoursesIndexRoute
  '/dashboard/student/quizzes/': typeof DashboardStudentQuizzesIndexRoute
  '/dashboard/teacher/courses/': typeof DashboardTeacherCoursesIndexRoute
  '/dashboard/teacher/quizzes/': typeof DashboardTeacherQuizzesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/courses/$id': typeof CoursesIdRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/dashboard/student/live': typeof DashboardStudentLiveRoute
  '/dashboard/student/orders': typeof DashboardStudentOrdersRoute
  '/dashboard/student/progress': typeof DashboardStudentProgressRoute
  '/dashboard/teacher/lessons': typeof DashboardTeacherLessonsRoute
  '/dashboard/teacher/live': typeof DashboardTeacherLiveRoute
  '/dashboard/teacher/progress': typeof DashboardTeacherProgressRoute
  '/dashboard/teacher/uploads': typeof DashboardTeacherUploadsRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/subscriptions': typeof AdminSubscriptionsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/dashboard/student': typeof DashboardStudentIndexRoute
  '/dashboard/teacher': typeof DashboardTeacherIndexRoute
  '/dashboard/student/courses/$id': typeof DashboardStudentCoursesIdRoute
  '/dashboard/student/quizzes/$id': typeof DashboardStudentQuizzesIdRoute
  '/dashboard/teacher/courses/$id': typeof DashboardTeacherCoursesIdRoute
  '/dashboard/teacher/courses/new': typeof DashboardTeacherCoursesNewRoute
  '/dashboard/teacher/quizzes/$id': typeof DashboardTeacherQuizzesIdRoute
  '/dashboard/student/courses': typeof DashboardStudentCoursesIndexRoute
  '/dashboard/student/quizzes': typeof DashboardStudentQuizzesIndexRoute
  '/dashboard/teacher/courses': typeof DashboardTeacherCoursesIndexRoute
  '/dashboard/teacher/quizzes': typeof DashboardTeacherQuizzesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/courses/$id': typeof CoursesIdRoute
  '/dashboard/student': typeof DashboardStudentRouteWithChildren
  '/dashboard/teacher': typeof DashboardTeacherRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/dashboard/student/live': typeof DashboardStudentLiveRoute
  '/dashboard/student/orders': typeof DashboardStudentOrdersRoute
  '/dashboard/student/progress': typeof DashboardStudentProgressRoute
  '/dashboard/teacher/courses': typeof DashboardTeacherCoursesRouteWithChildren
  '/dashboard/teacher/lessons': typeof DashboardTeacherLessonsRoute
  '/dashboard/teacher/live': typeof DashboardTeacherLiveRoute
  '/dashboard/teacher/progress': typeof DashboardTeacherProgressRoute
  '/dashboard/teacher/uploads': typeof DashboardTeacherUploadsRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/subscriptions/': typeof AdminSubscriptionsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/dashboard/student/': typeof DashboardStudentIndexRoute
  '/dashboard/teacher/': typeof DashboardTeacherIndexRoute
  '/dashboard/student/courses/$id': typeof DashboardStudentCoursesIdRoute
  '/dashboard/student/quizzes/$id': typeof DashboardStudentQuizzesIdRoute
  '/dashboard/teacher/courses/$id': typeof DashboardTeacherCoursesIdRoute
  '/dashboard/teacher/courses/new': typeof DashboardTeacherCoursesNewRoute
  '/dashboard/teacher/quizzes/$id': typeof DashboardTeacherQuizzesIdRoute
  '/dashboard/student/courses/': typeof DashboardStudentCoursesIndexRoute
  '/dashboard/student/quizzes/': typeof DashboardStudentQuizzesIndexRoute
  '/dashboard/teacher/courses/': typeof DashboardTeacherCoursesIndexRoute
  '/dashboard/teacher/quizzes/': typeof DashboardTeacherQuizzesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/register'
    | '/admin/categories'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/courses/$id'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/admin/'
    | '/courses/'
    | '/admin/courses/$id'
    | '/dashboard/student/live'
    | '/dashboard/student/orders'
    | '/dashboard/student/progress'
    | '/dashboard/teacher/courses'
    | '/dashboard/teacher/lessons'
    | '/dashboard/teacher/live'
    | '/dashboard/teacher/progress'
    | '/dashboard/teacher/uploads'
    | '/admin/courses/'
    | '/admin/subscriptions/'
    | '/admin/users/'
    | '/dashboard/student/'
    | '/dashboard/teacher/'
    | '/dashboard/student/courses/$id'
    | '/dashboard/student/quizzes/$id'
    | '/dashboard/teacher/courses/$id'
    | '/dashboard/teacher/courses/new'
    | '/dashboard/teacher/quizzes/$id'
    | '/dashboard/student/courses/'
    | '/dashboard/student/quizzes/'
    | '/dashboard/teacher/courses/'
    | '/dashboard/teacher/quizzes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/register'
    | '/admin/categories'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/courses/$id'
    | '/admin'
    | '/courses'
    | '/admin/courses/$id'
    | '/dashboard/student/live'
    | '/dashboard/student/orders'
    | '/dashboard/student/progress'
    | '/dashboard/teacher/lessons'
    | '/dashboard/teacher/live'
    | '/dashboard/teacher/progress'
    | '/dashboard/teacher/uploads'
    | '/admin/courses'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/dashboard/student/courses/$id'
    | '/dashboard/student/quizzes/$id'
    | '/dashboard/teacher/courses/$id'
    | '/dashboard/teacher/courses/new'
    | '/dashboard/teacher/quizzes/$id'
    | '/dashboard/student/courses'
    | '/dashboard/student/quizzes'
    | '/dashboard/teacher/courses'
    | '/dashboard/teacher/quizzes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/register'
    | '/admin/categories'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/courses/$id'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/admin/'
    | '/courses/'
    | '/admin/courses/$id'
    | '/dashboard/student/live'
    | '/dashboard/student/orders'
    | '/dashboard/student/progress'
    | '/dashboard/teacher/courses'
    | '/dashboard/teacher/lessons'
    | '/dashboard/teacher/live'
    | '/dashboard/teacher/progress'
    | '/dashboard/teacher/uploads'
    | '/admin/courses/'
    | '/admin/subscriptions/'
    | '/admin/users/'
    | '/dashboard/student/'
    | '/dashboard/teacher/'
    | '/dashboard/student/courses/$id'
    | '/dashboard/student/quizzes/$id'
    | '/dashboard/teacher/courses/$id'
    | '/dashboard/teacher/courses/new'
    | '/dashboard/teacher/quizzes/$id'
    | '/dashboard/student/courses/'
    | '/dashboard/student/quizzes/'
    | '/dashboard/teacher/courses/'
    | '/dashboard/teacher/quizzes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  CoursesIdRoute: typeof CoursesIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$id': {
      id: '/courses/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof CoursesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/student': {
      id: '/dashboard/student'
      path: '/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof DashboardStudentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/teacher': {
      id: '/dashboard/teacher'
      path: '/teacher'
      fullPath: '/dashboard/teacher'
      preLoaderRoute: typeof DashboardTeacherRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/$id': {
      id: '/admin/courses/$id'
      path: '/courses/$id'
      fullPath: '/admin/courses/$id'
      preLoaderRoute: typeof AdminCoursesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions/': {
      id: '/admin/subscriptions/'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions/'
      preLoaderRoute: typeof AdminSubscriptionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/student/': {
      id: '/dashboard/student/'
      path: '/'
      fullPath: '/dashboard/student/'
      preLoaderRoute: typeof DashboardStudentIndexRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/live': {
      id: '/dashboard/student/live'
      path: '/live'
      fullPath: '/dashboard/student/live'
      preLoaderRoute: typeof DashboardStudentLiveRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/orders': {
      id: '/dashboard/student/orders'
      path: '/orders'
      fullPath: '/dashboard/student/orders'
      preLoaderRoute: typeof DashboardStudentOrdersRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/progress': {
      id: '/dashboard/student/progress'
      path: '/progress'
      fullPath: '/dashboard/student/progress'
      preLoaderRoute: typeof DashboardStudentProgressRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/teacher/': {
      id: '/dashboard/teacher/'
      path: '/'
      fullPath: '/dashboard/teacher/'
      preLoaderRoute: typeof DashboardTeacherIndexRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
    '/dashboard/teacher/courses': {
      id: '/dashboard/teacher/courses'
      path: '/courses'
      fullPath: '/dashboard/teacher/courses'
      preLoaderRoute: typeof DashboardTeacherCoursesRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
    '/dashboard/teacher/lessons': {
      id: '/dashboard/teacher/lessons'
      path: '/lessons'
      fullPath: '/dashboard/teacher/lessons'
      preLoaderRoute: typeof DashboardTeacherLessonsRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
    '/dashboard/teacher/live': {
      id: '/dashboard/teacher/live'
      path: '/live'
      fullPath: '/dashboard/teacher/live'
      preLoaderRoute: typeof DashboardTeacherLiveRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
    '/dashboard/teacher/progress': {
      id: '/dashboard/teacher/progress'
      path: '/progress'
      fullPath: '/dashboard/teacher/progress'
      preLoaderRoute: typeof DashboardTeacherProgressRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
    '/dashboard/teacher/uploads': {
      id: '/dashboard/teacher/uploads'
      path: '/uploads'
      fullPath: '/dashboard/teacher/uploads'
      preLoaderRoute: typeof DashboardTeacherUploadsRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
    '/dashboard/student/courses/': {
      id: '/dashboard/student/courses/'
      path: '/courses'
      fullPath: '/dashboard/student/courses/'
      preLoaderRoute: typeof DashboardStudentCoursesIndexRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/courses/$id': {
      id: '/dashboard/student/courses/$id'
      path: '/courses/$id'
      fullPath: '/dashboard/student/courses/$id'
      preLoaderRoute: typeof DashboardStudentCoursesIdRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/quizzes/': {
      id: '/dashboard/student/quizzes/'
      path: '/quizzes'
      fullPath: '/dashboard/student/quizzes/'
      preLoaderRoute: typeof DashboardStudentQuizzesIndexRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/quizzes/$id': {
      id: '/dashboard/student/quizzes/$id'
      path: '/quizzes/$id'
      fullPath: '/dashboard/student/quizzes/$id'
      preLoaderRoute: typeof DashboardStudentQuizzesIdRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/teacher/courses/': {
      id: '/dashboard/teacher/courses/'
      path: '/'
      fullPath: '/dashboard/teacher/courses/'
      preLoaderRoute: typeof DashboardTeacherCoursesIndexRouteImport
      parentRoute: typeof DashboardTeacherCoursesRoute
    }
    '/dashboard/teacher/courses/$id': {
      id: '/dashboard/teacher/courses/$id'
      path: '/$id'
      fullPath: '/dashboard/teacher/courses/$id'
      preLoaderRoute: typeof DashboardTeacherCoursesIdRouteImport
      parentRoute: typeof DashboardTeacherCoursesRoute
    }
    '/dashboard/teacher/courses/new': {
      id: '/dashboard/teacher/courses/new'
      path: '/new'
      fullPath: '/dashboard/teacher/courses/new'
      preLoaderRoute: typeof DashboardTeacherCoursesNewRouteImport
      parentRoute: typeof DashboardTeacherCoursesRoute
    }
    '/dashboard/teacher/quizzes/': {
      id: '/dashboard/teacher/quizzes/'
      path: '/quizzes'
      fullPath: '/dashboard/teacher/quizzes/'
      preLoaderRoute: typeof DashboardTeacherQuizzesIndexRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
    '/dashboard/teacher/quizzes/$id': {
      id: '/dashboard/teacher/quizzes/$id'
      path: '/quizzes/$id'
      fullPath: '/dashboard/teacher/quizzes/$id'
      preLoaderRoute: typeof DashboardTeacherQuizzesIdRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCoursesIdRoute: typeof AdminCoursesIdRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
  AdminSubscriptionsIndexRoute: typeof AdminSubscriptionsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCoursesIdRoute: AdminCoursesIdRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
  AdminSubscriptionsIndexRoute: AdminSubscriptionsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardStudentRouteChildren {
  DashboardStudentLiveRoute: typeof DashboardStudentLiveRoute
  DashboardStudentOrdersRoute: typeof DashboardStudentOrdersRoute
  DashboardStudentProgressRoute: typeof DashboardStudentProgressRoute
  DashboardStudentIndexRoute: typeof DashboardStudentIndexRoute
  DashboardStudentCoursesIdRoute: typeof DashboardStudentCoursesIdRoute
  DashboardStudentQuizzesIdRoute: typeof DashboardStudentQuizzesIdRoute
  DashboardStudentCoursesIndexRoute: typeof DashboardStudentCoursesIndexRoute
  DashboardStudentQuizzesIndexRoute: typeof DashboardStudentQuizzesIndexRoute
}

const DashboardStudentRouteChildren: DashboardStudentRouteChildren = {
  DashboardStudentLiveRoute: DashboardStudentLiveRoute,
  DashboardStudentOrdersRoute: DashboardStudentOrdersRoute,
  DashboardStudentProgressRoute: DashboardStudentProgressRoute,
  DashboardStudentIndexRoute: DashboardStudentIndexRoute,
  DashboardStudentCoursesIdRoute: DashboardStudentCoursesIdRoute,
  DashboardStudentQuizzesIdRoute: DashboardStudentQuizzesIdRoute,
  DashboardStudentCoursesIndexRoute: DashboardStudentCoursesIndexRoute,
  DashboardStudentQuizzesIndexRoute: DashboardStudentQuizzesIndexRoute,
}

const DashboardStudentRouteWithChildren =
  DashboardStudentRoute._addFileChildren(DashboardStudentRouteChildren)

interface DashboardTeacherCoursesRouteChildren {
  DashboardTeacherCoursesIdRoute: typeof DashboardTeacherCoursesIdRoute
  DashboardTeacherCoursesNewRoute: typeof DashboardTeacherCoursesNewRoute
  DashboardTeacherCoursesIndexRoute: typeof DashboardTeacherCoursesIndexRoute
}

const DashboardTeacherCoursesRouteChildren: DashboardTeacherCoursesRouteChildren =
  {
    DashboardTeacherCoursesIdRoute: DashboardTeacherCoursesIdRoute,
    DashboardTeacherCoursesNewRoute: DashboardTeacherCoursesNewRoute,
    DashboardTeacherCoursesIndexRoute: DashboardTeacherCoursesIndexRoute,
  }

const DashboardTeacherCoursesRouteWithChildren =
  DashboardTeacherCoursesRoute._addFileChildren(
    DashboardTeacherCoursesRouteChildren,
  )

interface DashboardTeacherRouteChildren {
  DashboardTeacherCoursesRoute: typeof DashboardTeacherCoursesRouteWithChildren
  DashboardTeacherLessonsRoute: typeof DashboardTeacherLessonsRoute
  DashboardTeacherLiveRoute: typeof DashboardTeacherLiveRoute
  DashboardTeacherProgressRoute: typeof DashboardTeacherProgressRoute
  DashboardTeacherUploadsRoute: typeof DashboardTeacherUploadsRoute
  DashboardTeacherIndexRoute: typeof DashboardTeacherIndexRoute
  DashboardTeacherQuizzesIdRoute: typeof DashboardTeacherQuizzesIdRoute
  DashboardTeacherQuizzesIndexRoute: typeof DashboardTeacherQuizzesIndexRoute
}

const DashboardTeacherRouteChildren: DashboardTeacherRouteChildren = {
  DashboardTeacherCoursesRoute: DashboardTeacherCoursesRouteWithChildren,
  DashboardTeacherLessonsRoute: DashboardTeacherLessonsRoute,
  DashboardTeacherLiveRoute: DashboardTeacherLiveRoute,
  DashboardTeacherProgressRoute: DashboardTeacherProgressRoute,
  DashboardTeacherUploadsRoute: DashboardTeacherUploadsRoute,
  DashboardTeacherIndexRoute: DashboardTeacherIndexRoute,
  DashboardTeacherQuizzesIdRoute: DashboardTeacherQuizzesIdRoute,
  DashboardTeacherQuizzesIndexRoute: DashboardTeacherQuizzesIndexRoute,
}

const DashboardTeacherRouteWithChildren =
  DashboardTeacherRoute._addFileChildren(DashboardTeacherRouteChildren)

interface DashboardRouteChildren {
  DashboardStudentRoute: typeof DashboardStudentRouteWithChildren
  DashboardTeacherRoute: typeof DashboardTeacherRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardStudentRoute: DashboardStudentRouteWithChildren,
  DashboardTeacherRoute: DashboardTeacherRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  CoursesIdRoute: CoursesIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
